### ISSUE TITLE
Laravel Scout not deleting models

### ISSUE THREAD

**Issue by Jon78** [constantable/laravel-scout-sphinx#3]
Updating an unsearchable model triggers the delete() function. Since the SphinxQL-driver expects an array for the model key, and an integer is given, this function breaks:

>  Argument 1 passed to Foolz\SphinxQL\Drivers\ConnectionBase::quoteArr() must be of the type array, integer given

**Comment by constantable** [comment]
Thanks for PR. Just merged it
